server:
  port: 10100


spring:
  application:
    name: auth-server
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/nacos?useUnicode=true&useSSL=false&characterEncoding=utf8
    url: jdbc:mysql://localhost:3306/user_db?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: 2018@Jura

# redis 配置，在实际使用中host 要修改成实际的redis地址
  redis:
    password:
    host: localhost

security:
  oauth2:
    resource:
      filter-order: 3

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:10003/eureka/


# 暴露监控端点
management:
  endpoints:
    web:
      exposure:
        include: '*'


logging:
  level:
    com: DEBUG
    org: DEBUG