server:
  port: 10104

spring:
  application:
    name: admin-biz

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:10003/eureka/

## spring security 配置
security:
  oauth2:
    client:
      client-id: aiqiyi
      client-secret: secret
      scope: server
      # 默认放行url,如果子模块重写这里的配置就会被覆盖
      ignore-urls:
        - /actuator/**
        - /v2/api-docs
        - /users/none
    resource:
      loadBalanced: true
      token-info-uri: http://localhost:10100/oauth/check_token

logging:
  level:
    com: DEBUG
    org: DEBUG